name: Variables de entorno
on: {push}
jobs:
  verify_errors:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting node version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Linter execution
        uses:  github/super-linter@v4
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm install jest && npm test
  environment_test_execution:
    env: 
      DESTINATION_PERSON: "2DAW"
    runs-on: ubuntu-latest
    steps:
      - name: environment
        uses: adeloyedeji/github-actions-hello@v1
        with: 
          who-to-greet: ${{ env.DESTINATION_PERSON }}